#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from thrift_gen.ttypes import *

# CHARGES
BALANCE_INFO_CHARGES = 0.2

# DAILY WITHDRAWAL LIMIT
DAILY_WITHDRAWL_LIMIT = 850